protected/modules/admin/controllers/ConfigController.php
<?php

class ConfigController extends MainAdminController
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index','update'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);

		if( Yii::app()->request->hasPost('Config')) {
			$model->attributes = Yii::app()->request->post('Config');
			if ($model->save()) {
                $this->redirect(array('index'));
            }
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model = new Config('search');
		$model->unsetAttributes();  // clear any default values
		if (Yii::app()->request->hasGet('Config')) {
            $model->attributes = Yii::app()->request->get('Config');
        }

		$this->render('index',array(
			'model' => $model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Config the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Config::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
}

protected/modules/admin/controllers/DefaultController.php
<?php

class DefaultController extends MainAdminController
{
	public function actionIndex()
	{
        $totalUsers = User::model()->count();
        $totalProblems = Problem::model()->count();
        $totalArticles = Article::model()->count();

		$this->render('index', array(
            'totalUsers'    => $totalUsers,
            'totalProblems' => $totalProblems,
            'totalArticles' => $totalArticles,
        ));
	}

    public function actionSearch($text)
    {
        $news_model = new News('search');
        $news_model->title_ru = $text;

        $article_model = new Article('search');
        $article_model->title_ru = $text;

        $problem_model = new Problem('search');
        $problem_model->name_ru = $text;

        $this->render('search', array(
            'news_model'    => $news_model,
            'article_model' => $article_model,
            'problem_model' => $problem_model,
        ));
    }
}

protected/modules/admin/views/config/_form.php
<?php
/* @var $this ConfigController */
/* @var $model Config */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php
    $form = $this->beginWidget(
        'booster.widgets.TbActiveForm'
    );
    ?>

        <?php if ($model->type == 'boolean'): ?>
            <?php echo $form->switchGroup($model, 'value',
                array(
                    'label' => Yii::t('interface','Значение:')
                )
            ); ?>
        <?php elseif ($model->type == 'textarea'): ?>
            <?php
            echo $form->textAreaGroup(
                $model,
                'value',
                array(
                    'widgetOptions' => array(
					    'htmlOptions' => array('rows' => 10),
				    ),
                    'label'     => Yii::t('interface','Значение:')
                )
            );
            ?>
        <?php else: ?>
            <?php
            echo $form->textFieldGroup(
                $model,
                'value',
                array(
                    'size'      => 60,
                    'maxlength' => 255,
                    'label'     => Yii::t('interface','Значение:')
                )
            );
            ?>
        <?php endif; ?>

        <div class="form-group text-center" style="margin-top: 20px;">
            <?php
            $this->widget(
                'booster.widgets.TbButton',
                array(
                    'buttonType' => 'submit',
                    'context'    => 'success',
                    'label'      => Yii::t('interface','Сохранить')
                )
            );
            ?>

            <?php
            echo CHtml::link(
                Yii::t('interface','Вернуться'),
                $this->createUrl('config/index'),
                array(
                    'class' => 'btn btn-danger'
                )
            );
            ?>
        </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/admin/views/config/index.php
<?php
/* @var $this ConfigController */
/* @var $model Config */

$this->main_header = Yii::t('interface','Manage Configs');

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика') => $this->createUrl('default/index'),
    Yii::t('interface', 'Настройки')  => '#',
);
?>

<?php
$this->renderGridView(array(
    'id'            => 'config-grid',
    'model'         => $model,
    'columns'       => array(
        array(
            'name' => 'label',
            'value' => '$data->label',
            'header' => 'Параметр',
            'htmlOptions' => array('style' => 'width: 30%;'),
        ),
        array(
            'name' => 'value',
            'value' => '($data->type=="boolean") ? ($data->value ? "Да" : "Нет") : ($data->type=="textarea" ? (substr($data->value, 0, 150) . (strlen($data->value) > 150 ? "..." : "")) : $data->value)',
            'header' => 'Значение',
            'filter' => false,
        ),
        array(
            'htmlOptions' => array('nowrap'=>'nowrap'),
            'class'       => 'booster.widgets.TbButtonColumn',
            'buttons'     => array(
                'delete'    => array(
                    'visible' => ''
                ),
                'view'    => array(
                    'visible' => ''
                )
            )
        ),
    )
));
?>

protected/modules/admin/views/config/update.php
<?php
/* @var $this ConfigController */
/* @var $model Config */

$this->main_header = 'Редактирование настройки "' . $model->param . '"';

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')               => $this->createUrl('default/index'),
    Yii::t('interface', 'Настройки')                => $this->createUrl('config/index'),
    Yii::t('interface', 'Редактировать настройку')  => '#',
);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>