protected/modules/admin/controllers/DefaultController.php
<?php

class DefaultController extends MainAdminController
{
	public function actionIndex()
	{
        $totalUsers = User::model()->count();
        $totalProblems = Problem::model()->count();
        $totalArticles = Article::model()->count();

		$this->render('index', array(
            'totalUsers'    => $totalUsers,
            'totalProblems' => $totalProblems,
            'totalArticles' => $totalArticles,
        ));
	}

    public function actionSearch($text)
    {
        $news_model = new News('search');
        $news_model->title_ru = $text;

        $article_model = new Article('search');
        $article_model->title_ru = $text;

        $problem_model = new Problem('search');
        $problem_model->name_ru = $text;

        $this->render('search', array(
            'news_model'    => $news_model,
            'article_model' => $article_model,
            'problem_model' => $problem_model,
        ));
    }
}

protected/modules/admin/controllers/NewsController.php
<?php

class NewsController extends MainAdminController
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view','admin','delete','create','update'),
                'users'=>array('*'),
            ),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new News;

		if (Yii::app()->request->hasPost('News')) {
			$model->attributes=Yii::app()->request->post('News');
			if ($model->save()) {
                $this->redirect(array('news/'));
            }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);

		if(Yii::app()->request->hasPost('News')) {
			$model->attributes=Yii::app()->request->post('News');
			if ($model->save()) {
                $this->redirect(array('news/'));
            }
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
    {
        $this->loadModel($id)->delete();
        NewsComment::model()->deleteAllByAttributes(array('n_id' => $id));

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!Yii::app()->request->hasGet('ajax')) {
            $this->redirect(Yii::app()->request->hasPost('returnUrl') ? Yii::app()->request->post('returnUrl') : array('news/'));
        }
    }

	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model = new News('search');
        $model->dbCriteria->order='id DESC';
		$model->unsetAttributes();  // clear any default values
		if(Yii::app()->request->hasGet('News')) {
            $model->attributes = Yii::app()->request->get('News');
        }

		$this->render('index',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return News the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=News::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
}

protected/modules/admin/views/news/_form.php
<?php
/* @var $this NewsController */
/* @var $model News */
/* @var $form CActiveForm */
?>

<div class="form">
    <?php
    $form = $this->beginWidget(
        'booster.widgets.TbActiveForm'
    );
    ?>

		<?php echo $form->textFieldGroup($model,'title_ru',array('size'=>60,'maxlength'=>255, 'label' => 'Заглавие (рус.):')); ?>

		<?php echo $form->textFieldGroup($model,'title_ro',array('size'=>60,'maxlength'=>255, 'label' => 'Заглавие (рум.):')); ?>

        <?php echo $form->ckEditorGroup(
            $model,
            'text_ru',
            array(
                'widgetOptions' => array(
                    'htmlOptions' => array('style'=>'height: 150px;')
                ),
                'label' => 'Текст (рус.):'
            )
        ); ?>

        <?php echo $form->ckEditorGroup(
            $model,
            'text_ro',
            array(
                'widgetOptions' => array(
                    'htmlOptions' => array('style'=>'height: 150px;')
                ),
                'label' => 'Текст (рум.):'
            )
        ); ?>

        <?php echo $form->dropDownListGroup(
            $model,
            'type',
            array(
                'widgetOptions' => array(
                    'data' => MNews::getNewsTypes()
                )
            )
        ); ?>

        <?php echo $form->switchGroup($model, 'hide',
            array(
                'label' => 'Скрыта:'
            )
        ); ?>

        <div class="form-group text-center" style="margin-top: 20px;">
            <?php
            $this->widget(
                'booster.widgets.TbButton',
                array(
                    'buttonType' => 'submit',
                    'context'    => 'success',
                    'label'      => $model->isNewRecord ? Yii::t('interface','Создать') : Yii::t('interface','Сохранить')
                )
            );
            ?>

            <?php
            echo CHtml::link(
                Yii::t('interface','Вернуться'),
                $this->createUrl('news/index'),
                array(
                    'class' => 'btn btn-danger'
                )
            );
            ?>
        </div>
    <?php $this->endWidget(); ?>
</div><!-- form -->

protected/modules/admin/views/news/create.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->main_header = Yii::t('interface','Создание новости');

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')      => $this->createUrl('default/index'),
    Yii::t('interface', 'Список новостей') => $this->createUrl('news/index'),
    Yii::t('interface', 'Создать новость') => '#',
);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/news/index.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->main_header = Yii::t('interface','Manage News');

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')      => $this->createUrl('default/index'),
    Yii::t('interface', 'Список новостей') => '#'
);
?>

<?php
$this->renderGridView(array(
    'id'            => 'news-grid',
    'model'         => $model,
    'columns'       => array(
        'id',
        array(
            'name'   => 'title_ru',
            'value'  => '$data->title_ru',
            'header' => 'Название (рус.)',
        ),
        array(
            'name'   => 'title_ro',
            'value'  => '$data->title_ro',
            'header' => 'Название (рум.)',
        ),
        array(
            'name'          => 'created',
            'value'         => 'date("j.m.Y",$data->created)',
            'header'        => 'Создано',
            'htmlOptions'   => array(
                'style'     => 'text-align: center;',
            ),
        ),
        array(
            'name'          => 'hide',
            'value'         => '($data->hide)?"Да":"Нет"',
            'header'        => 'Скрыто',
            'htmlOptions'   => array(
                'style'     => 'text-align: center;',
            ),
            'filter' => array(
                0 => "Нет",
                1 => "Да",
            ),
        ),
        array(
            'htmlOptions' => array('nowrap'=>'nowrap'),
            'class'       => 'booster.widgets.TbButtonColumn',
        ),
    )
));
?>

protected/modules/admin/views/news/update.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->main_header = Yii::t('interface','Редактирование новости') . ' "' . $model->title . '"';

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')            => $this->createUrl('default/index'),
    Yii::t('interface', 'Список новостей')       => $this->createUrl('news/index'),
    Yii::t('interface', 'Редактировать новость') => '#',
);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/news/view.php
<?php
/* @var $this NewsController */
/* @var $model News */

$this->main_header = Yii::t('interface','View News #') . $model->id;

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')       => $this->createUrl('default/index'),
    Yii::t('interface', 'Список новостей')  => $this->createUrl('news/index'),
    Yii::t('interface', 'Просмотр новости') => '#',
);
?>

<?php $this->widget('booster.widgets.TbDetailView', array(
	'data'       => $model,
	'attributes' => array(
        array('name' => 'id', 'label' => Yii::t('interface', 'ID')),
        array('name' => 'title_ru', 'label' => Yii::t('interface', 'Название (ru)')),
        array('name' => 'title_ro', 'label' => Yii::t('interface', 'Название (ro)')),
        array('name' => 'text_ru', 'label' => Yii::t('interface', 'Текст (ru)'), 'type'=>'raw'),
        array('name' => 'text_ro', 'label' => Yii::t('interface', 'Текст (ro)'), 'type'=>'raw'),
        array('name' => 'created', 'label' => Yii::t('interface', 'Создан'), 'value' => Yii::app()->dateFormatter->formatDateTime($model->created)),
        array('name' => 'hide', 'label' => Yii::t('interface', 'Скрыт'), 'value' => ($model->hide)? Yii::t('interface', 'Да') : Yii::t('interface', 'Нет')),
	),
)); ?>