protected/models/Solution.php
<?php

/**
 * This is the model class for table "{{solution}}".
 *
 * The followings are the available columns in table '{{solution}}':
 * @property integer $id
 * @property string $u_id
 * @property string $p_id
 * @property integer $time_send
 * @property string $result
 * @property string $tests
 * @property string $log_compile
 * @property integer $status
 * @property string $compiler
 * @property string $file_name
 * @property string $file_text
 * @property string $problemName
 * @property string $userLogin
 * @property string $file_solution
 * @property string $text_solution
 * @property string $upload_mode
 * @property integer $max_result
 * @property Problem $problem
 * @property User $user
 */
class Solution extends CActiveRecord
{
    const STATUS_WAITING_COMPILING = 1;
    const STATUS_COMPILING = 2;
    const STATUS_WAITING_TESTING = 3;
    const STATUS_TESTING = 4;
    const STATUS_FINISH = 5;
    const STATUS_COMPILE_ERROR = 10;

    const STATUS_CONTEST_WAITING_PRE_COMPILING = 21;
    const STATUS_CONTEST_PRE_COMPILING = 22;
    const STATUS_CONTEST_COMPILE_ERROR = 23;
    const STATUS_CONTEST_WAITING_PRE_TESTING = 24;
    const STATUS_CONTEST_PRE_TESTING = 25;
    const STATUS_CONTEST_FAIL_PRE_TESTING = 26;
    const STATUS_CONTEST_ACCEPT_PRE_TESTING = 27;
    const STATUS_CONTEST_WAITING_COMPILING = 28;
    const STATUS_CONTEST_COMPILING = 29;
    const STATUS_CONTEST_WAITING_TESTING = 30;
    const STATUS_CONTEST_TESTING = 31;
    const STATUS_CONTEST_FINISH = 32;

    public $problemName;

    public $userLogin;

    public $file_solution;

    public $text_solution;

    public $upload_mode;

    public $max_result = 0;

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'a_solution';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('time_send, status', 'numerical', 'integerOnly'=>true),
			array('u_id, p_id, result', 'length', 'max'=>10),
			array('tests, log_compile, compiler, file_text', 'safe'),
            array('file_solution', 'required', 'on' => 'sendSolutionFile'),
            array('text_solution', 'required', 'on' => 'sendSolutionText'),
            array('compiler, upload_mode', 'required', 'on' => 'sendSolutionText, sendSolutionFile'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, u_id, p_id, time_send, result, tests, log_compile, status, compiler, problemName, userLogin', 'safe', 'on'=>'search'),
			array('id, u_id, p_id, time_send, result, status, compiler, problemName, userLogin', 'safe', 'on'=>'searchPlainForUser'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'user'=>array(self::BELONGS_TO, 'User', 'u_id'),
            'problem'=>array(self::BELONGS_TO, 'Problem', 'p_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id'            => 'ID',
			'u_id'          => 'U',
			'p_id'          => 'P',
			'time_send'     => 'Time Send',
			'result'        => 'Result',
			'tests'         => 'Tests',
			'log_compile'   => 'Log Compile',
			'status'        => 'Status',
            'compiler'      => Yii::t('interface','Компилятор'),
            'file_solution' => Yii::t('interface','Файл'),
            'upload_mode'   => Yii::t('interface','Метод'),
            'text_solution' => Yii::t('interface','Решение'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('t.id',$this->id);
		$criteria->compare('u_id',$this->u_id);
		$criteria->compare('p_id',$this->p_id);
		$criteria->compare('result',$this->result);
		$criteria->compare('tests',$this->tests);
		$criteria->compare('log_compile',$this->log_compile);
		$criteria->compare('status',$this->status);
        $criteria->compare('compiler',$this->compiler);
        $criteria->compare('problem.name',$this->problemName);
        $criteria->compare('user.login',$this->userLogin);
        $criteria->with = array('problem', 'user');

        $time_send = DateTime::createFromFormat('j.m.Y', $this->time_send);
        if ($time_send) {
            $criteria->addBetweenCondition('time_send', $time_send->getTimestamp(), $time_send->modify('+1 day')->getTimestamp());
        } else {
            $criteria->compare('time_send',$this->time_send);
        }

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
            'sort'=>array(
                'defaultOrder'=>array(
                    'id'=>"DESC"
                )
            ),
		));
	}

    /**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function searchPlainForUser()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('t.id',$this->id);
		$criteria->compare('u_id',$this->u_id);
		$criteria->compare('p_id',$this->p_id);
		$criteria->compare('result',$this->result);
		$criteria->compare('status',$this->status);
        $criteria->compare('compiler',$this->compiler);
        $criteria->compare('problem.name',$this->problemName);
        $criteria->compare('user.login',$this->userLogin);
        $criteria->with = array('problem', 'user');

        $time_send = DateTime::createFromFormat('j.m.Y', $this->time_send);
        if ($time_send) {
            $criteria->addBetweenCondition('time_send', $time_send->getTimestamp(), $time_send->modify('+1 day')->getTimestamp());
        } else {
            $criteria->compare('time_send',$this->time_send);
        }

        $criteria->addBetweenCondition('status', Solution::STATUS_WAITING_COMPILING, Solution::STATUS_COMPILE_ERROR);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
            'sort'=>array(
                'defaultOrder'=>array(
                    'id'=>"DESC"
                )
            ),
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Solution the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

    /**
     * @return bool
     */
    protected function beforeSave(){
        if (parent::beforeSave()) {
            if ($this->isNewRecord) {
                $this->time_send = time();
            } else {
                $this->tests = json_encode($this->tests);
            }
            return true;
        }
        return false;
    }

    /**
     * Method that handle sent solutions
     *
     * @param bool $contest
     * @param null $contest_problem_id
     * @return bool
     */
    public function createNewSolution($contest = false, $contest_problem_id = null){
        $this->u_id = Yii::app()->user->id;
        $this->file_name = $this->filename();

        if ($this->upload_mode == 'file') {
            if (mb_detect_encoding(file_get_contents($this->file_solution->tempName), 'UTF-8', true) === false) {
                $this->file_text = iconv('windows-1251', 'utf-8', file_get_contents($this->file_solution->tempName));
            } else {
                $this->file_text = file_get_contents($this->file_solution->tempName);
            }
        }else{
            $this->file_text = $this->text_solution;
        }

        if ($contest) {
            $this->status = self::STATUS_CONTEST_WAITING_PRE_COMPILING;
        }else{
            $this->status = self::STATUS_WAITING_COMPILING;
        }

        $this->save();

        if ($contest){
            $contest_solution = new ContestSolution();
            $contest_solution->contest_problem_id = $contest_problem_id;
            $contest_solution->solution_id = $this->id;
            $contest_solution->save();
        }

        return true;
    }

    /**
     * @return string
     */
    private function filename(){
        switch($this->compiler){
            case 'FPC':
                return '1.pas';
            case 'GCC':
                return '1.c';
            case 'Prolog':
                return '1.pl';
            case 'G++':
                return '1.cpp';
            case 'Java':
                return 'Main.java';
            default:
                return '1.undefined';
        }
    }

    /**
     * @return string
     */
    public function getExtension(){
        switch($this->compiler){
            case 'FPC':
                return '.pas';
            case 'GCC':
                return '.c';
            case 'Prolog':
                return '.pl';
            case 'G++':

protected/controllers/ProblemController.php
<?php

class ProblemController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
        $model = MProblem::loadPublicModel($id);
        $modelForm = new Solution('sendSolutionText');

        if (Yii::app()->request->hasPost('Solution') && Yii::app()->config->get('SEND.SOLUTION')){
            $modelForm->attributes = Yii::app()->request->getPost('Solution');
            if ($modelForm->upload_mode == 'file') {
                $modelForm->file_solution = CUploadedFile::getInstance($modelForm, 'file_solution');
                $modelForm->scenario = 'sendSolutionFile';
            }
            $modelForm->p_id = $model->id;
            if ($modelForm->validate()){
                $modelForm->createNewSolution();
                $this->redirect(array('solution/index','pid'=>$model->id));
            }
        }

        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/problemView.js');
		$this->render('view',array(
			'model'         => $model,
            'modelForm'     => $modelForm,
            'sendForbidden' => MProblem::getSendForbiddenMessage(),
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionIndex()
	{
		$model=new Problem('search');
		$model->unsetAttributes();  // clear any default values
		if (Yii::app()->request->hasGet('Problem')) {
            $model->attributes = Yii::app()->request->get('Problem');
        }

		$this->render('index',array(
			'model'=>$model,
		));
	}
}

protected/controllers/SolutionController.php
<?php

class SolutionController extends Controller
{
    public $layout='//layouts/column2';

    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view', 'download'),
                'users'=>array('@'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

	public function actionIndex($pid = NULL)
	{
        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js', CClientScript::POS_END);
        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/libs/bootstrap-datepicker/locales/bootstrap-datepicker.en-GB.min.js', CClientScript::POS_END);
        Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/libs/bootstrap-datepicker/css/bootstrap-datepicker3.min.css');

        $model = new Solution('searchPlainForUser');
        $model->unsetAttributes();  // clear any default values

        $model->u_id = Yii::app()->user->id;
        if ($pid) {
            $model->p_id = $pid;
        }

        if (Yii::app()->request->hasGet('Solution')) {
            $model->attributes = Yii::app()->request->get('Solution');
        }

        $this->render('index',array(
            'model' => $model,
        ));
	}

	public function actionView($id)
	{
        // Connect HighLighter
        Yii::app()->syntaxhighlighter->addHighlighter();
        //Connect ZeroClipboard
        Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/libs/ZeroClipboard/ZeroClipboard.min.js');

        $this->render('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    /**
     * @param $id
     * @return mixed
     * @throws CHttpException
     */
    public function actionDownload($id){
        $model = $this->loadModel($id);
        return Yii::app()->getRequest()->sendFile($model->problem->name . $model->getExtension(), $model->file_text);
    }

    /**
     * @param $id
     * @return Solution
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model=Solution::model()->findByAttributes(array('id' => $id, 'u_id' => Yii::app()->user->id));
        if($model===null)
            throw new CHttpException(404,'The requested page does not exist.');
        return $model;
    }
}

protected/views/solution/index.php
<?php
/* @var $this SolutionController */
/* @var $dataProvider CActiveDataProvider */
/* @var $model Solution */

$this->menu = array(
    array('label'=>Yii::t('interface', 'Список задач'), 'url'=>array('problem/index')),
    array('label'=>Yii::t('interface', 'Отправленные решения'), 'url'=>array('solution/index')),
);
?>

<h1 class="text-center"><?php echo Yii::t('interface','Отправленные решения');?></h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
    'id'            => 'solution-grid',
    'dataProvider'  => $model->searchPlainForUser(),
    'filter'        => $model,
    'columns'       => array(
        array(
            'name'  => 'id',
            'value' => '$data->id',
            'header'=> 'ID',
        ),
        array(
            'name'  => 'p_id',
            'value' => '$data->problem ? $data->problem->name : \'-\'',
            'header'=> Yii::t('interface','Задача'),
            'filter'=> CHtml::listData(Problem::model()->findAll(),'id','name'),
        ),
        array(
            'name'  => 'time_send',
            'value' => 'date("j.m.Y",$data->time_send)',
            'header'=> Yii::t('interface','Время отправки'),
        ),
        array(
            'name'  => 'status',
            'value' => '$data->getStatusName()',
            'header'=> Yii::t('interface','Статус'),
            'filter'=> array(
                Solution::STATUS_WAITING_COMPILING  => Yii::t('interface','Ожидание'),
                Solution::STATUS_COMPILING          => Yii::t('interface','Компилирование'),
                Solution::STATUS_WAITING_TESTING    => Yii::t('interface','Ожидание тестирования'),
                Solution::STATUS_TESTING            => Yii::t('interface','Тестирование'),
                Solution::STATUS_FINISH             => Yii::t('interface','Завершено'),
                Solution::STATUS_COMPILE_ERROR      => Yii::t('interface','Ошибка компиляции'),
            )
        ),
        array(
            'name'  => 'compiler',
            'value' => '$data->compiler',
            'header'=> Yii::t('interface','Компилятор'),
            'filter'=> CHtml::listData($model->findAll(), 'compiler', 'compiler'),
        ),
        array(
            'name'  => 'result',
            'value' => '$data->result',
            'header'=> Yii::t('interface','Результат'),
        ),
        array(
            'class'     => 'CButtonColumn',
            'template'  => '{view}',
        ),
    ),
    'itemsCssClass' => 'table table-hover table-bordered',
    'pagerCssClass' => 'text-center',
    'summaryText'   => '',
    'pager'         =>array(
        'htmlOptions' => array(
            'class' => 'pagination'
        ),
        'header'                => '',
        'maxButtonCount'        => 25,
        'selectedPageCssClass'  => 'active',
        'hiddenPageCssClass'    => 'disabled',
        'firstPageLabel'        => '&lt;&lt;',
        'lastPageLabel'         => '&gt;&gt;',
        'prevPageLabel'         => false,
        'nextPageLabel'         => false,
    ),
    'afterAjaxUpdate' => 'function(){$(\'input[name="Solution[time_send]"]\').datepicker({format: \'dd.mm.yyyy\', autoclose: true});}',
)); ?>

<script>
    $(function(){
        $('input[name="Solution[time_send]"]').datepicker({format: 'dd.mm.yyyy', autoclose: true});
    });

    $(document).ajaxStart(function () {
        $("#solution-grid")
            .find("thead *[name^='Solution']").attr("readonly", true).end()
            .find("thead select[name^='Solution']").attr("disabled", true);
    });
    $(document).ajaxComplete(function () {
        $("#solution-grid")
            .find("thead *[name^='Solution']").attr("readonly", false).end()
            .find("thead select[name^='Solution']").attr("disabled", false);
    });
</script>

protected/views/solution/view.php
<?php
/* @var $this SolutionController */
/* @var $dataProvider CActiveDataProvider */
/* @var $model Solution */
?>
<div class="row">
    <div class="col-md-5">
        <div style="padding-top: 12px;">
            <a href="<?php echo $this->createUrl('solution/index'); ?>"><button class="btn btn-default">
                <i class="fa fa-chevron-left"></i> <?php echo Yii::t('interface', 'Назад'); ?>
            </button></a>

            <a href="<?php echo $this->createUrl('problem/view', array('id' => $model->p_id)); ?>"><button class="btn btn-default">
                <i class="fa fa-file-text-o"></i> <?php echo Yii::t('interface', 'Описание задачи'); ?>
            </button></a>
        </div>
    </div>
    <div class="col-md-2 text-center">
        <h1>"<?php echo $model->problem ? $model->problem->name : '-'; ?>"</h1>
    </div>
</div>

<?php $this->widget('zii.widgets.CDetailView', array(
    'data'=>$model,
    'attributes'=>array(
        array(
            'name' => 'time_send',
            'value' => date("j.m.Y", $model->time_send),
            'label' => Yii::t('interface','Время отправки'),
        ),
        array(
            'name' => 'status',
            'value' => $model->getStatusName(),
            'label' => Yii::t('interface','Статус'),
        ),
        array(
            'name' => 'result',
            'value' => $model->result,
            'label' => Yii::t('interface','Результат'),
        ),
        array(
            'name' => 'compiler',
            'value' => $model->compiler,
            'label' => Yii::t('interface','Компилятор'),
        ),
        array(
            'name' => 'log_compile',
            'value' => $model->log_compile,
            'label' => Yii::t('interface','Лог компилятора'),
            'type' => 'html',
        ),
    ),
));?>
<br>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title text-center">
            <?php echo Yii::t('interface','Тесты');?>
        </h3>
    </div>
    <div class="panel-body">
        <table class="table table-hover">
            <tr class="active">
                <td><b><?php echo Yii::t('interface','Тест');?></b></td>
                <td><b><?php echo Yii::t('interface','Результат');?></b></td>
            </tr>
            <?php for ($i=1; $i <= ($model->problem ? $model->problem->tests : 10); $i++): ?>
                <tr class="<?php echo $model->getTrClassByResult($i);?>">
                    <td><?php echo $i; ?></td>
                    <td><?php echo (!empty($model->tests) && array_key_exists($i, $model->tests)) ? $model->getResultStatusName($i) . ' ('.$model->tests[$i][1].' с.)' : "-"; ?></td>
                </tr>
            <?php endfor; ?>
        </table>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title text-center">
            <?php echo Yii::t('interface','Код');?>
        </h3>
    </div>
    <div class="panel-body" style="padding: 0;">
        <pre class="brush : <?php echo $model->getLanguageByCompiler(); ?>"><?php echo CHtml::encode($model->file_text); ?></pre>
    </div>
    <div class="panel-footer">
        <button id="copy-button" data-clipboard-text="<?php echo CHtml::encode($model->file_text);?>" tabindex="0" class="btn btn-default" data-toggle="popover" data-trigger="focus" data-content="<?php echo Yii::t('interface','Код был скопирован');?>"><?php echo Yii::t('interface','Скопировать код');?></button>
        <button id="download-button" class="btn btn-default"><a href="<?php echo $this->createUrl('solution/download', array('id' => $model->id));?>"><?php echo Yii::t('interface','Скачать код');?></a></button>
    </div>
</div>

<?php if ($model->getNotification()): ?>
    <div class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-info-sign"></span> <?php echo $model->getNotification();?></div>
<?php endif; ?>

<script>
    var client = new ZeroClipboard( $("#copy-button") );
</script>