protected/modules/admin/controllers/ArticleController.php
<?php

class ArticleController extends MainAdminController
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','admin','delete','create','update'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Article;

		if (Yii::app()->request->hasPost('Article')) {
			$model->attributes=Yii::app()->request->post('Article');
			if ($model->save()) {
                $this->redirect(array('article/'));
            }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);

		if (Yii::app()->request->hasPost('Article')) {
			$model->attributes=Yii::app()->request->post('Article');
			if ($model->save()) {
                $this->redirect(array('article/'));
            }
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!Yii::app()->request->hasGet('ajax')) {
            $this->redirect(Yii::app()->request->hasPost('returnUrl') ? Yii::app()->request->post('returnUrl') : array('article/'));
        }
    }

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
        $model = new Article('search');
        $model->unsetAttributes();  // clear any default values
        if (Yii::app()->request->hasGet('Article')) {
            $model->attributes = Yii::app()->request->get('Article');
        }

        $this->render('index',array(
            'model'=>$model,
        ));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Articles the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Article::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
}

protected/modules/admin/controllers/DefaultController.php
<?php

class DefaultController extends MainAdminController
{
	public function actionIndex()
	{
        $totalUsers = User::model()->count();
        $totalProblems = Problem::model()->count();
        $totalArticles = Article::model()->count();

		$this->render('index', array(
            'totalUsers'    => $totalUsers,
            'totalProblems' => $totalProblems,
            'totalArticles' => $totalArticles,
        ));
	}

    public function actionSearch($text)
    {
        $news_model = new News('search');
        $news_model->title_ru = $text;

        $article_model = new Article('search');
        $article_model->title_ru = $text;

        $problem_model = new Problem('search');
        $problem_model->name_ru = $text;

        $this->render('search', array(
            'news_model'    => $news_model,
            'article_model' => $article_model,
            'problem_model' => $problem_model,
        ));
    }
}

protected/modules/admin/views/article/_form.php
<?php
/* @var $this ArticleController */
/* @var $model Article */
/* @var $form CActiveForm */
?>

<div class="form">
    <?php
    $form = $this->beginWidget(
        'booster.widgets.TbActiveForm'
    );
    ?>

        <?php echo $form->textFieldGroup($model,'title_ru',array('size'=>60,'maxlength'=>255, 'label' => 'Заглавие (рус.):')); ?>

        <?php echo $form->textFieldGroup($model,'title_ro',array('size'=>60,'maxlength'=>255, 'label' => 'Заглавие (рум.):')); ?>

        <?php echo $form->ckEditorGroup(
            $model,
            'text_ru',
            array(
                'widgetOptions' => array(
                    'htmlOptions' => array('style'=>'height: 150px;')
                ),
                'label' => 'Текст (рус.):'
            )
        ); ?>

        <?php echo $form->ckEditorGroup(
            $model,
            'text_ro',
            array(
                'widgetOptions' => array(
                    'htmlOptions' => array('style'=>'height: 150px;')
                ),
                'label' => 'Текст (рум.):'
            )
        ); ?>

        <?php echo $form->switchGroup($model, 'hide',
            array(
                'label' => 'Скрыта:'
            )
        ); ?>

        <?php echo $form->dropDownListGroup(
            $model,
            'g_id',
            array(
                'widgetOptions' => array(
                    'data' => CHtml::listData(GroupArticle::model()->findAll(), 'id' ,'title'),
                    'htmlOptions' => array(),
                ),
                'label' => 'Группа статей:'
            )
        ); ?>

        <div class="form-group text-center" style="margin-top: 20px;">
            <?php
            $this->widget(
                'booster.widgets.TbButton',
                array(
                    'buttonType'=> 'submit',
                    'context'   => 'success',
                    'label'     => $model->isNewRecord ? Yii::t('interface','Создать') : Yii::t('interface','Сохранить')
                )
            );
            ?>

            <?php
            echo CHtml::link(
                Yii::t('interface','Вернуться'),
                $this->createUrl('article/index'),
                array(
                    'class' => 'btn btn-danger'
                )
            );
            ?>
        </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/admin/views/article/create.php
<?php
/**
 * @var Article $model
 */

$this->main_header = Yii::t('interface','Создание статьи');

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')       => $this->createUrl('default/index'),
    Yii::t('interface', 'Список статей')    => $this->createUrl('article/index'),
    Yii::t('interface', 'Создание статьи')  => '#',
);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/article/index.php
<?php
/**
 * @var Article $model
 */

$this->main_header = Yii::t('interface','Manage Article');

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')     => $this->createUrl('default/index'),
    Yii::t('interface', 'Список статей')  => '#',
);
?>

<?php
$this->renderGridView(array(
    'id'            => 'article-grid',
    'model'         => $model,
    'columns'       => array(
        'id',
        array(
            'name'   => 'title_ru',
            'value'  => '$data->title_ru',
            'header' => 'Название (рус.)',
        ),
        array(
            'name'   => 'title_ro',
            'value'  => '$data->title_ro',
            'header' => 'Название (рум.)',
        ),
        array(
            'name'   => 'hide',
            'value'  => '($data->hide)?"Да":"Нет"',
            'header' => 'Скрыто',
            'htmlOptions' => array(
                'style' => 'text-align: center;',
            ),
            'filter' => array(
                0 => "Нет",
                1 => "Да",
            ),
        ),
        array(
            'name' => 'groupTitle',
            'value' => '$data->groupArticle->title_'.Yii::app()->getUser()->getLanguage(),
        ),
        array(
            'htmlOptions' => array('nowrap'=>'nowrap'),
            'class'=>'booster.widgets.TbButtonColumn',
        ),
    )
));
?>

protected/modules/admin/views/article/update.php
<?php
/**
 * @var Article $model
 */

$this->main_header = 'Редактирование статьи "' . $model->title . '"';

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')             => $this->createUrl('default/index'),
    Yii::t('interface', 'Список статей')          => $this->createUrl('article/index'),
    Yii::t('interface', 'Редактирование статьи')  => '#',
);
?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/article/view.php
<?php
/**
 * @var Article $model
 */

$this->main_header = Yii::t('interface','View Article #') . $model->id;

$this->breadcrumbs = array(
    Yii::t('interface', 'Статистика')       => $this->createUrl('default/index'),
    Yii::t('interface', 'Список статей')    => $this->createUrl('article/index'),
    Yii::t('interface', 'Просмотр статьи')  => '#',
);
?>

<?php $this->widget('booster.widgets.TbDetailView', array(
    'data'       => $model,
    'attributes' => array(
        array('name' => 'id', 'label' => Yii::t('interface', 'ID')),
        array('name' => 'title_ru', 'label' => Yii::t('interface', 'Название (ru)')),
        array('name' => 'title_ro', 'label' => Yii::t('interface', 'Название (ro)')),
        array('name' => 'text_ru', 'label' => Yii::t('interface', 'Текст (ru)'), 'type'=>'raw'),
        array('name' => 'text_ro', 'label' => Yii::t('interface', 'Текст (ro)'), 'type'=>'raw'),
        array('name' => 'groupTitle', 'label' => Yii::t('interface', 'Группа'), 'value' => $model->groupArticle->title),
        array('name' => 'hide', 'label' => Yii::t('interface', 'Скрыта'), 'value' => ($model->hide)? Yii::t('interface', 'Да') : Yii::t('interface', 'Нет')),
    ),
)); ?>